BookShop/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from reference.views import (Index, CreateAuthorView, UpdateAuthorView, DetailAuthorView, ListAuthorView, 
DeleteAuthorView, )
from products.views import (CreateBook, UpdateBook, DetailBook, ListBook, DeleteBook) 
from core.views import UserHomeTemplateView, AboutTemplateView, DeliveryTemplateView
from adminecore.views import StaffHomeTemplateView 

urlpatterns = [
    url('main-admin/', admin.site.urls),

    path('admin/ref/', include('reference.urls', namespace="reference")),
    path('admin/prod/', include('products.urls')),
    path('admin/', StaffHomeTemplateView.as_view()),
    
    path('user/', UserHomeTemplateView.as_view()),
    path('user/cart/', include('cart.urls')),
    path('user/order/', include('order.urls')),
    path('user/comments/', include('comments.urls')),
    path('user/search/', include('search.urls', namespace="search")),

    path('user/core/', include('core.urls', namespace="core")),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # redirect_url
# get_success_url(self):
# return  reverse_lazy(...., kwargs={pk = self.obj.id})
# get_request

# google material design


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),

#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),

#     ] + urlpatterns

cart/urls.py
from django.urls import path
from . import views
from .views import (AddProductToCartView, CartView, DelOrderView )


app_name = "cart"

urlpatterns = [
    path('add/<int:book>/', AddProductToCartView.as_view(), name="add"),
    path('bookcart/', CartView.as_view(), name="bookcart"),
    path('del/<int:pk>/', DelOrderView.as_view(), name="delete"),
]





    

order/urls.py
from django.urls import path
from . import views
from .views import (OrderCheckoutView, OrderCheckoutSuccess, OrdersListAdmin)


app_name = "order"

urlpatterns = [
    
    #path('incart/', OrderView.as_view(), name='order-in-cart'),
    path(
        'check-out/',
        views.OrderCheckoutView.as_view(),
        name="check-out"),
    path(
        'success/<int:pk>/',
        views.OrderCheckoutSuccess.as_view(),
        name="success"),

    path(
        'list-admin/',
        OrdersListAdmin.as_view(),
        name="list-admin"),

        ]
        # сделать ссылку на главной c object.pk/ статус в хтмл {{ object.status.name }}
#        1. гет контекст из детаил вью: выдергивает объект (order)
#        гет контекст выдает словарь (значения объекта)
#        гет контекст дата - влази в конец, перед отрисовкой страницы (лучше для меню и прочего)
#        2. второй вариант через гет_обджект (получает объект из модели, предпочтительнее для работы с объектами! )
#
# новая тема
#пагинация - постранично (для больших объемов!)
# paginate_by = 2 (по 2 объекта на странице)
# миксин занимается обработкой данных
# например миксин для отображения списка объектов (постранично)
# в урлах номер страницы
# специальное слово last (т.к. не изместно количество страниц)
# orphans - допис последнюю страницу (новая или предпоследн большая)
# в контекст - обджект-лист, ин-паджинэитыд, пагинатор
# {{ is.paginated }} boolean (сейчас работает ли пагинация - тру/да) для отображения кнопок важно 
# {{ paginator }}    
# можно добавить шаблон и инклудить его на все страницы, где будет пагинация
#
# новая тема
# аутентификация (кто ты? логин/пароль)   
# аутеризация (процесс узнавания того, что мне разрешено)
# админ, персонал, покупатель2
# next - возврат после логина на страницу, с которой перебросило на логин 


    
    

products/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import (CreateBook, UpdateBook, DetailBook, ListBook, 
DeleteBook, )
# from .apptoview import ListBooks

app_name = "products"

urlpatterns = [
    path('book/create/', CreateBook.as_view(), name = "book-create"),
    path('book/detail/<int:pk>/', DetailBook.as_view(), name = "book-detail"),
    path('book/list/', ListBook.as_view(), name = "book-list"),
    path('book/update/<int:pk>/', UpdateBook.as_view(), name = "book-update"),
    path('book/delete/<int:pk>/', DeleteBook.as_view(), name = "book-delete"),

#    path('book/listbooks/<int:pk>/', ListBooks.as_view(), name = "listbooks"),
] 

#if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

adminecore/models.py
from django.db import models

# Create your models here.

adminecore/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic.base import TemplateView

class StaffHomeTemplateView(TemplateView):
    template_name = "staff-home.html"
    def get_context_data(self, **kwargs):
        context = super(StaffHomeTemplateView, self).get_context_data(**kwargs)
        menuitems = {
            'name': 'Справочники',
            'items': [
                {'item': 'Авторы',
                'url': '/admin/ref/bookauthor/list/'},
                {'item': 'Серии',
                'url': '/admin/ref/bookseries/list/'},
                {'item': 'Жанры',
                'url': '/admin/ref/genre/list/'},
                {'item': 'Издательства',
                'url': '/admin/ref/publisher/list/'},
                {'item': 'Изготовитель',
                'url': '/admin/ref/maker/list/'},
                {'item': 'Статус заказа',
                'url': '/admin/ref/status/list/'}
            ]
        }
        context ['menu'] = menuitems
        context['logo'] = "BOOKshop"
        #print(type(context))
        return context

    

    
'''class DetailMakerView(DetailView):
    template_name = 'detail-base-ref.html'
    model = Maker
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['descr'] = 'Изготовитель'
        return context'''

adminecore/templates/base-staff.html
{% load static %}
{% load crispy_forms_tags %}
{% load my_tags %}
{% load comment %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block head %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="navbar-brand" href="/user/">{% include 'logo.html' %}</a></li>
                <li class="nav-item active"><a class="nav-link" href="/admin/">Справочники</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'products:book-list'%}">Книги</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'order:list-admin' %}">Заказы</a></li>
            </ul>

        <form class="">
                {% if user.is_authenticated %}
                {{ user.username }}
                {% endif %}
            <button class="btn btn-outline-info btn-sm" type="submit">Выйти</button>
        </form>
        </div>
    </nav>
            
    {% block content %}
    {% endblock %}

    <script src="https://unpkg.com/ionicons@4.5.0/dist/ionicons.js"></script>
</body>
</html>

adminecore/templates/staff-home.html
{% extends "base-staff.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block title %}
Админпортал
{% endblock title %}
    

{% block content %}    
<br>

    <div class="container">
        <h6 class="alert alert-info" role="alert"><i class="fas fa-puzzle-piece"></i> {{ menu.name }}</h6>
            {% if menu.items %}
                <ul class="list-group">
                    {% for item in menu.items %}
                    <li class="list-group-item"><a href="{{ item.url }}">{{ item.item }}</a></li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

    
{% endblock content %}    