BookShop/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from reference.views import (Index, CreateAuthorView, UpdateAuthorView, DetailAuthorView, ListAuthorView, 
DeleteAuthorView, )
from products.views import (CreateBook, UpdateBook, DetailBook, ListBook, DeleteBook) 
from core.views import UserHomeTemplateView, AboutTemplateView, DeliveryTemplateView
from adminecore.views import StaffHomeTemplateView 

urlpatterns = [
    url('main-admin/', admin.site.urls),

    path('admin/ref/', include('reference.urls', namespace="reference")),
    path('admin/prod/', include('products.urls')),
    path('admin/', StaffHomeTemplateView.as_view()),
    
    path('user/', UserHomeTemplateView.as_view()),
    path('user/cart/', include('cart.urls')),
    path('user/order/', include('order.urls')),
    path('user/comments/', include('comments.urls')),
    path('user/search/', include('search.urls', namespace="search")),

    path('user/core/', include('core.urls', namespace="core")),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # redirect_url
# get_success_url(self):
# return  reverse_lazy(...., kwargs={pk = self.obj.id})
# get_request

# google material design


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),

#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),

#     ] + urlpatterns

cart/urls.py
from django.urls import path
from . import views
from .views import (AddProductToCartView, CartView, DelOrderView )


app_name = "cart"

urlpatterns = [
    path('add/<int:book>/', AddProductToCartView.as_view(), name="add"),
    path('bookcart/', CartView.as_view(), name="bookcart"),
    path('del/<int:pk>/', DelOrderView.as_view(), name="delete"),
]





    

products/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import (CreateBook, UpdateBook, DetailBook, ListBook, 
DeleteBook, )
# from .apptoview import ListBooks

app_name = "products"

urlpatterns = [
    path('book/create/', CreateBook.as_view(), name = "book-create"),
    path('book/detail/<int:pk>/', DetailBook.as_view(), name = "book-detail"),
    path('book/list/', ListBook.as_view(), name = "book-list"),
    path('book/update/<int:pk>/', UpdateBook.as_view(), name = "book-update"),
    path('book/delete/<int:pk>/', DeleteBook.as_view(), name = "book-delete"),

#    path('book/listbooks/<int:pk>/', ListBooks.as_view(), name = "listbooks"),
] 

#if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

products/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
import re
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime
# Create your models here.

def my_validator(val):
    if val != 5:
        raise ValidationError('Price must be 5')

'''def isbn_validator(val):
    if val != 13:
        raise ValidationError('Lenght ISBN must be 13')

def isbn_validator(val): 
    if len(val) != 13 
    if val != re.match('\d{13}', val):
    pass
    else:
        raise ValidationError('Неправильный ISBN')'''

class Book(models.Model):
    name = models.CharField(
        verbose_name = "Название книги",
        max_length=50
    )
    photo = models.ImageField(
        verbose_name = "Фото обложки",
#        upload_to='static/', 
        )
    cost = models.DecimalField( 
        verbose_name = "Цена (BYN)",
        decimal_places=2, 
        max_digits=5,
        #validators=[my_validator],
    )
    author = models.ManyToManyField(
        'reference.BookAuthor', 
        verbose_name="Автор(ы)",
    )
    description = models.CharField(
        verbose_name = "Описание",
        max_length=250,
    )
    series = models.ForeignKey(
        'reference.BookSeries', 
        verbose_name="Серия",
        null=True, 
        blank=True,
        on_delete=models.CASCADE
    )
    genre = models.ManyToManyField(
        'reference.Genre', 
        verbose_name="Жанр(ы)",
    )
    imprintdate = models.PositiveIntegerField(
        verbose_name = "Год издания",
        validators=[
            MinValueValidator(1900, message="Укажите год позднее 1900."),
            MaxValueValidator(datetime.datetime.now().year, message="Указанный год не может больше текущего."),
        ],
        default=2018
    )
    pagecount = models.PositiveIntegerField(
        verbose_name = "Количество страниц",
        default=300
    )
    cover = models.CharField(
        verbose_name = "Переплет",
        max_length=10
    )
    bookformat = models.CharField(
        verbose_name = "Формат",
        max_length=20
    )
    isbn = models.CharField(
        verbose_name = "ISBN",
        max_length=20,
#        validators=[isbn_validator],
    )
    weight = models.IntegerField( 
        verbose_name = "Вес (гр)"
    )
    agelimit = models.IntegerField( 
        verbose_name = "Возрастные ограничения"
    )
    publisher = models.ForeignKey(
        'reference.Publisher', 
        verbose_name="Издательство",
        on_delete=models.CASCADE
    )
    maker = models.ForeignKey(
        'reference.Maker', 
        verbose_name="Изготовитель",
        on_delete=models.CASCADE
    )
    bookquantity = models.PositiveIntegerField(
        verbose_name = "Количество книг в наличии",
        default=0
    )
    active = models.BooleanField(
        verbose_name = "Активный (доступен для заказа)",
        default=True
    )
    promotion = models.BooleanField(
        verbose_name = "товар на акции",
    )
    ratio = models.FloatField( 
        verbose_name = "Рейтинг (1-10)"
    )
    dateadd = models.DateTimeField(
        verbose_name = "Дата внесения в каталог",
        default=timezone.now
    )
    dateuppdate = models.DateTimeField(
        verbose_name = "Дата последнего изменения карточки",
        blank=True, null=True
    )
    def __str__(self):
        return self.name

products/forms.py
from django import forms

from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'name', 
            'photo', 
            'cost',
            'author',
            'description',
            'series',
            'genre',
            'imprintdate',
            'pagecount',
            'cover',
            'bookformat',
            'isbn',
            'weight',
            'agelimit',
            'publisher',
            'maker',
            'bookquantity', 
            'active',
            'promotion',
            'ratio',
            'dateadd',
            'dateuppdate'
        ]
    '''def get_view_url(self):
        return "/admin/ref/bookseries/detail/{}/".format(self.pk)
    def get_update_url(self):
        return "/admin/ref/bookseries/update/{}/".format(self.pk)
    def get_delete_url(self):
        return "/admin/ref/bookseries/delete/{}/".format(self.pk)'''
'''
def clean_cost(self):
    cleaned_data = super().clean()
    cost = self.cleaned_data.get ("cost")
    # import validation error from django
    if cost != 5:
        raise ValidationError("Cost 5")'''

def clean(self):
    cleaned_data = super().clean()
    cost = self.cleaned_data.get ("cost")
    # import validation error from django
    if cost != 5:
        self.add_error('cost', '5')
        raise ValidationError("Cost 5")
    return cleaned_data

products/views.py
from django.shortcuts import render
from django.views.generic import (CreateView, UpdateView, DetailView, ListView, DeleteView)
from .forms import BookForm
from .models import Book

from datetime import datetime, date, time, timedelta

class CreateBook(CreateView):
    form_class=BookForm
    template_name = 'create-update-book.html'
    success_url = '/admin/prod/book/list/'
    def get_context_data(self, *args, **kwargs):
        context = super(CreateBook, self).get_context_data(*args, **kwargs)
        context['ref_action'] = 'Добавление книги'
        context['logo'] = "BOOKshop"
        return context

class ListBook(ListView):
    template_name = 'list-base-book.html'
    model = Book
    paginate_by = 5
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['descr'] = 'Список книг'
        context['count_books'] = self.model.objects.all().count()
        context['active_books'] = self.model.objects.filter(active=True).count()
        x = datetime.now()-timedelta(days=1)
        context['add_books'] = self.model.objects.filter(dateadd__gt=x).count()
        y = datetime.now()-timedelta(days=30)
        context['add_books_month'] = self.model.objects.filter(dateadd__gt=y).count()
        context['logo'] = "BOOKshop"
        return context

class DetailBook(DetailView):
    template_name = 'detail-base-book.html'
    model = Book
    form_class = BookForm
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['descr'] = 'Книга'
        context['logo'] = "BOOKshop"
        return context

class UpdateBook(UpdateView):
    template_name = 'create-update-book.html'
    form_class = BookForm
    model = Book
    success_url = '/admin/prod/book/list/'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['ref_action'] = 'Редактирование книги'
        context['temp'] = self.kwargs
        context['logo'] = "BOOKshop"
        return context

class DeleteBook(DeleteView):
    template_name = 'delete-base-book.html'
    model = Book
    success_url = '/admin/prod/book/list/'
    def get_context_data(self, *args, **kwargs):
        context = super(DeleteBook, self).get_context_data(*args, **kwargs)
#        context = super().get_context_data(*args, **kwargs)
        context['delete'] = 'Удалить'
        context['logo'] = "BOOKshop"
        return context

products/templates/create-update-book.html
{% extends "base-staff.html" %}
{% load crispy_forms_tags %}

{% load static %}

{% block head %}
{% endblock head %}

{% block title %}
Новая книга
{% endblock title %}
    
{% block body %}    
{% block content %}

    <div class="container">
        </br>
        <h4 class="alert alert-info" role="alert">{{ ref_action }}</h4>
        <p><small>Поля, отмеченные звездочкой *, обязательны для заполнения.</small></p>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-info">Отправить</button>
            <a href="{% url 'products:book-list' %}"><button type="button" class="btn btn-outline-info">Назад</button></a>
        </form>
    </div>
    </br>

{% endblock content %}    
{% endblock body %}

products/templates/delete-base-book.html
{% extends "base-staff.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block title %}
Удаление {{ object.name }}
{% endblock title %}
    
{% block body %}
    {% block content %}    

<div class="container">
    </br>
    <form action="" method="POST">
        {% csrf_token %}
        <h4 class="alert alert-info" role="alert">{{ delete }} "{{ object.name }}"?</h4>
        <input class="btn btn-outline-danger" type="submit" value="ДА">
        <a href="{% url 'products:book-list' %}"><button type="button" class="btn btn-outline-info">НЕТ</button></a>
    </form>
</div>
{% endblock content %}    

{% endblock body %}

products/templates/detail-base-book.html
{% extends "base-staff.html" %}
{% load static %}

{% block head %}
{% endblock head %}

{% block title %}
{{ object.name }}
{% endblock title %}
    
{% block body %}
{% block content %}    

<div class="container">
    </br>
    <h4 class="alert alert-info" role="alert">{{ descr }} "{{ object.name }}"</h4>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th scope="row" class="col-sm-3">Обложка:</th>
                <td class="col-sm-9"><img src="{{ object.photo.url }}" class="img-thumbnail" alt="обложка" ></td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Цена:</th>
                <td class="col-sm-9">{{ object.cost }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Автор:</th>
                <td class="col-sm-9">{{ object.author.all|join:", " }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Серия:</th>
                <td class="col-sm-9">{{ object.series }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Жанр:</th>
                <td class="col-sm-9">{{ object.genre.all|join:", " }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Год издания:</th>
                <td class="col-sm-9">{{ object.imprintdate }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Количество страниц:</th>
                <td class="col-sm-9">{{ object.pagecount }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Переплет:</th>
                <td class="col-sm-9">{{ object.cover }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Формат:</th>
                <td class="col-sm-9">{{ object.bookformat }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">isbn:</th>
                <td class="col-sm-9">{{ object.isbn }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Вес:</th>
                <td class="col-sm-9">{{ object.weight }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Возрастные ограничения:</th>
                <td class="col-sm-9">{{ object.agelimit }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Издательство:</th>
                <td class="col-sm-9">{{ object.publisher }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Изготовитель:</th>
                <td class="col-sm-9">{{ object.maker }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Количество книг:</th>
                <td class="col-sm-9">{{ object.bookquantity }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Активный (доступен для заказа):</th>
                <td class="col-sm-9">{{ object.active }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Товар на акции:</th>
                <td class="col-sm-9">{{ object.promotion }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Рейтинг:</th>
                <td class="col-sm-9">{{ object.ratio }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Дата внесения в каталог:</th>
                <td class="col-sm-9">{{ object.dateadd }}</td>
            </tr>
            <tr>
                <th scope="row" class="col-sm-3">Дата последнего изменения карточки:</th>
                <td class="col-sm-9">{{ object.dateuppdate }}</td>
            </tr>
        </tbody>
    </table>        
    </br>
    <a href="{% url 'products:book-list' %}"><button type="button" class="btn btn-outline-info">Назад</button></a>
    </br>
    </br>
</div>
{% endblock content %}    

{% endblock body %}

products/templates/list-base-book.html
{% extends "base-staff.html" %}
{% load static %}

{% block head %}
{% endblock head %}

{% block title %}
Список книг
{% endblock title %}
    

{% block content %}    

<div class="container">
    </br>
    <div class="card" style="width: 28rem;">
        <div class="card-body">
            <h4 class="alert alert-warning" role="alert">Статистика по разделу </h4>
            <p>Общее количество книг: {{ count_books }}</p>
            <p>Количество активных (доступных для заказа) книг: {{ active_books }}.</p>
            <p>Количество добавленных книг за прошлый день: {{ add_books }}.</p>
            <p>Количество добавленных книг за прошлый месяц: {{ add_books_month }}.</p>
        </div>
    </div>
    </br>
    <h4 class="alert alert-info" role="alert">{{ descr }}</h4>
    <table class="table table-borderless">
        {% for object in object_list %}
            <tr>
                <td>{{ object.name }}</td>
                <td><a href="{% url 'products:book-detail' object.pk %}"><button type="button" class="btn btn-light">Просмотр</button></a></td>
                <td><a href="{% url 'products:book-update' object.pk %}"><button type="button" class="btn btn-light">Редактирование</button></a></td>
                <td><a href="{% url 'products:book-delete' object.pk %}"><button type="button" class="btn btn-outline-dark">Удаление</button></a></td>
            </tr>
        {% endfor %}
        <tr><td><a href="{% url 'products:book-create' %}"><button type="button" class="btn btn-outline-info">Добавить новую книгу</button></a></td></tr>
    </table>
    
    {% include 'pagination.html' %}

    <!-- 
    {{ is_paginated }}
    {{ paginator.page_range }}
    {{ paginator.num_pages }}
    {{ page_obj.has_next }}
-->
<!--{% if is_paginated %}
        <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                  <li class="page-item">
                        <a class="page-link" href="{% url 'products:book-list' %}?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                  </li>
                  {% else %}
                  <li class="page-item">

                      </li>
                  {% endif %}

{% for page in paginator.page_range %}
{% if page == page_obj.number %}
                  <li class="page-item active"><a class="page-link" href="{% url 'products:book-list' %}?page={{ page }}">{{ page }}</a></li>
{% else %}
<li class="page-item"><a class="page-link" href="{% url 'products:book-list' %}?page={{ page }}">{{ page }}</a></li>



{% endif %}
{% endfor %}




                  {% if page_obj.has_next %}
                  <li class="page-item">
                        <a class="page-link" href="{% url 'products:book-list' %}?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
                  </li>
                  {% else %}
                  <li class="page-item">

                    </li>
                    {% endif %}
                </ul>
              </nav>

{% endif %}

-->
</div>

{% endblock content %}    