BookShop/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from reference.views import (Index, CreateAuthorView, UpdateAuthorView, DetailAuthorView, ListAuthorView, 
DeleteAuthorView, )
from products.views import (CreateBook, UpdateBook, DetailBook, ListBook, DeleteBook) 
from core.views import UserHomeTemplateView, AboutTemplateView, DeliveryTemplateView
from adminecore.views import StaffHomeTemplateView 

urlpatterns = [
    url('main-admin/', admin.site.urls),

    path('admin/ref/', include('reference.urls', namespace="reference")),
    path('admin/prod/', include('products.urls')),
    path('admin/', StaffHomeTemplateView.as_view()),
    
    path('user/', UserHomeTemplateView.as_view()),
    path('user/cart/', include('cart.urls')),
    path('user/order/', include('order.urls')),
    path('user/comments/', include('comments.urls')),
    path('user/search/', include('search.urls', namespace="search")),

    path('user/core/', include('core.urls', namespace="core")),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # redirect_url
# get_success_url(self):
# return  reverse_lazy(...., kwargs={pk = self.obj.id})
# get_request

# google material design


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),

#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),

#     ] + urlpatterns

cart/urls.py
from django.urls import path
from . import views
from .views import (AddProductToCartView, CartView, DelOrderView )


app_name = "cart"

urlpatterns = [
    path('add/<int:book>/', AddProductToCartView.as_view(), name="add"),
    path('bookcart/', CartView.as_view(), name="bookcart"),
    path('del/<int:pk>/', DelOrderView.as_view(), name="delete"),
]





    

core/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import LoginView, LogoutView
# from .views import ProfileView
from core.views import UserHomeTemplateView, AboutTemplateView, DeliveryTemplateView

app_name = "core"

urlpatterns = [

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.view_profile, name='view_profile'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('delivery/', DeliveryTemplateView.as_view(), name='delivery'),
    
    ] 

products/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import (CreateBook, UpdateBook, DetailBook, ListBook, 
DeleteBook, )
# from .apptoview import ListBooks

app_name = "products"

urlpatterns = [
    path('book/create/', CreateBook.as_view(), name = "book-create"),
    path('book/detail/<int:pk>/', DetailBook.as_view(), name = "book-detail"),
    path('book/list/', ListBook.as_view(), name = "book-list"),
    path('book/update/<int:pk>/', UpdateBook.as_view(), name = "book-update"),
    path('book/delete/<int:pk>/', DeleteBook.as_view(), name = "book-delete"),

#    path('book/listbooks/<int:pk>/', ListBooks.as_view(), name = "listbooks"),
] 

#if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

search/urls.py
from django.urls import path
from . import views
from .views import (SearchView, SearchResultsView)

app_name = "search"

urlpatterns = [
    path('search/', SearchView.as_view(), name = "search"),
    path('search-results/', SearchResultsView.as_view(), name = "search-results"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# Create your models here.
# User = get_user_model()

# class Profile(models.Model):
#     user =  models.OneToOneField(
#         User,
#         on_delete=models.CASCADE)
#     username = models.CharField(
#         verbose_name = "Имя",
#         max_length=50
#     )
#     userphone = models.CharField(
#         verbose_name="Телефон",
#         max_length=30)
#     useremail = models.EmailField(
#         verbose_name="Электронная почта",
#         null=True,
#         blank=True,
#         )
#     useraddress = models.TextField(
#         "Адрес доставки",
#         null=True,
#         blank=True,
#         )

core/forms.py
from django import forms
from django.forms import ModelForm
# from .models import Profile


# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = [
#             'username',
#             'userphone',
#             'useremail',
#             'useraddress',
#         ]
#     def __init__(self, user, *args, **kwargs):
#         self.user = user.profile

core/views.py
from django.shortcuts import render
from django.views.generic import (CreateView, UpdateView, DetailView, ListView, DeleteView)
# from .models import Profile
# from .forms import ProfileForm

# Create your views here.

from django.views.generic.base import TemplateView
from products.models import Book

class UserHomeTemplateView(TemplateView):
    template_name = "user-home.html"
    def get_context_data(self, **kwargs):
        context = super(UserHomeTemplateView, self).get_context_data(**kwargs)
        last_book = Book.objects.all()
        #[4:]
        context['last_book'] = last_book
        return context

class AboutTemplateView(TemplateView):
    template_name = "about.html"
    def get_context_data(self, **kwargs):
        context = super(AboutTemplateView, self).get_context_data(**kwargs)
        context['logo'] = "BOOKshop"
        return context

class DeliveryTemplateView(TemplateView):
    template_name = "delivery.html"
    def get_context_data(self, **kwargs):
        context = super(DeliveryTemplateView, self).get_context_data(**kwargs)
        return context

class CartTemplateView(TemplateView):
    template_name = "add-to-cart.html"
    def get_context_data(self, **kwargs):
        context = super(CartTemplateView, self).get_context_data(**kwargs)
        return context


# class ProfileView(DetailView):
#     model = Profile
#     form_class = ProfileForm
#     template_name = 'profile.html'
#     def get_context_data(self, *args, **kwargs):
#         context = super().get_context_data(*args, **kwargs)
#         context['descr'] = 'Кабинет пользователя'
#         return context

def view_profile(request):
    args = {'user': request.user}
    return render(request, 'profile.html', args)

core/templates/about.html
{% extends "base-core.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block title %}
BookShop 
{% endblock title %}
   

{% block content %}
    
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">BOOKShop рад видеть Вас!</h1>
    <p class="lead">Компания BOOKShop является одиним из крупнейших белорусских книжных интернет-магазинов. 
            Наша задача — предложить клиенту идеальный сервис и максимальный выбор: товаров, способов оплаты, вариантов доставки.
            Сегодня ассортимент книг насчитывает более 190 позиций. Появившись около 2 месяцев назад, BOOKShop стал одним из первых белорусских интернет-магазинов и первым книжным интернет-магазином.</p>
    <p class="lead">Юридический адрес: 220001, г. Минск, пр-т Независимости, д. 1.</p>
    <p class="lead">Электронный адрес: chytach@bookshop.by</p>
  </div>
</div>
        
{% endblock content %}

core/templates/base-core.html
{% load static %}
{% load crispy_forms_tags %}
{% load my_tags %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block head %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="navbar-brand" href="/user/">{% include 'logo.html' %}</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'products:book-list'%}">Книги</a></li>
                <li class="nav-item active"><a class="nav-link" href="/user/">Акции</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'core:delivery' %}">Доставка</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'core:about' %}">О компании</a></li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                {% top_cart_icon %}
            </form>

            {% if user.is_authenticated %}
            <a class="btn btn-outline-info btn-sm" href="{% url 'core:view_profile' %}"><i class="far fa-address-card"></i> {{ user.username }} </a>
            <a class="btn btn-outline-info btn-sm" href="{% url 'core:logout' %}">Выход</a>
            {% else %}
            <a class="btn btn-outline-info btn-sm" href="{% url 'core:login' %}">Вход</a>
            {% endif %}

        </div>
    </nav>

    {% block contentmain %}
    {% endblock %}

    <div class="container">
        <br>
    <form method="GET" action="{% url 'search:search-results' %}" class="form-inline my-2 my-lg-0">
        <input type="text" name="q" class="form-control form-control-sm-2" type="search" placeholder="Поиск" aria-label="Search">
        <button class="btn btn-outline-info" type="submit"><i class="fas fa-search"></i></button>
    </form>
    <br>
    </div>

    {% block content %}
    {% endblock %}

    <script src="https://unpkg.com/ionicons@4.5.0/dist/ionicons.js"></script>
</body>
</html>

core/templates/delivery.html
{% extends "base-core.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block title %}
BookShop доставка 
{% endblock title %}
    
{% block content %}
    
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Виды доставки</h1>
        <p class="lead">Курьером по Минску (бесплатно от 30 руб.) Доставка курьером по Минску осуществляется в пределах МКАД.
Вы выбираете удобное время доставки из возможных вариантов — и мы доставим заказ в течение 3 указанных часов. 
Бесплатная доставка при стоимости товаров в заказе от 30,00 руб. Стоимость 5,00 руб.</p>
        <p class="lead">Самовывоз с г. Минск, пр-т Независимости, д. 1.</p>    
        <p class="lead">Почтой по Беларуси (14 — 21 день). Заказ высылается почтой по территории Беларуси на Ваш адрес после того, 
как мы получим подтверждение его оплаты. В населенных пунктах, где нет доставки курьером и пунктов самовывоза, 
возможен наложенный платеж (оплата по факту получения товара). Стоимость согласно тарифов РУП БелПочта для юридических лиц.</p>
    </div>
</div>
        
{% endblock content %}

core/templates/logo.html
<h4>B<i class="fab fa-tripadvisor"></i>kShop </h4>

core/templates/profile.html
{% extends "base-core.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block title %}
Вход
{% endblock title %}
    
{% block content %}


<div class="container">
<br>
   <h4 class="alert alert-info" role="alert">{{ user.username }}</h4>
   
   <table class="table table-striped">
      <tbody>
          <tr>
              <th scope="row" class="col-sm-3">Телефон:</th>
              <td class="col-sm-9">{{ user.userphone }}</td>
          </tr>
          <tr>
            <th scope="row" class="col-sm-3">Электронная почта:</th>
            <td class="col-sm-9">{{ user.email }}</td>
          </tr>
          <tr>
            <th scope="row" class="col-sm-3">Адрес:</th>
            <td class="col-sm-9">{{ user.useraddress }}</td>
          </tr>
          <tr>
            <th scope="row" class="col-sm-3">Дата регистрации:</th>
            <td class="col-sm-9">{{ user.date_joined }}</td>
          </tr>
          <tr>
            <th scope="row" class="col-sm-3">Последний вход:</th>
            <td class="col-sm-9">{{ user.last_login }}</td>
          </tr>
      </tbody>
  </table>        

</div>
{% endblock content %}

core/templates/top_cart_icon.html
<a class="nav-link" href="{% url 'cart:bookcart' %}">
    {% if products > 0 %}
    <span class="btn btn-outline-danger btn-sm" >Корзина ({{ products }})</span> 
{% else %}
    <span class="btn btn-outline-info btn-sm">Корзина ({{ products }})</span> 
{% endif %}

core/templates/user-home.html
{% extends "base-core.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block title %}
BookShop 
{% endblock title %}
    
{% block contentmain %}
<div class="jumbotron jumbotron-fluid" >
    <div class="container">
        <h1 class="display-4">BOOKShop рад видеть Вас!</h1>
        <p class="lead">{% if user.is_authenticated %}
        {{ user.username }}{% endif %}, в разделе <a href="{% url 'products:book-list'%}">Книги</a> Вы найдете все, что Вас интересует.</p>
    </div>
</div>
{% endblock contentmain %}
{% block content %}
<div class="container">
    <div class="card-group">      
        {% for book in last_book %}
            <div class="card" >
                <img class="card-img-top" src="{{ book.photo.url }}"  height="280" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{ book.name }}</h5>
                    <p class="card-text">Цена: {{ book.cost }}</p>
                    <a href="{% url 'cart:add' book.pk %}" class="btn btn-warning btn-sm">Купить</a>
                    <a href="{% url 'products:book-detail' book.pk %}" class="btn btn-info btn-sm">Просмотр</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}