BookShop/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from reference.views import (Index, CreateAuthorView, UpdateAuthorView, DetailAuthorView, ListAuthorView, 
DeleteAuthorView, )
from products.views import (CreateBook, UpdateBook, DetailBook, ListBook, DeleteBook) 
from core.views import UserHomeTemplateView, AboutTemplateView, DeliveryTemplateView
from adminecore.views import StaffHomeTemplateView 

urlpatterns = [
    url('main-admin/', admin.site.urls),

    path('admin/ref/', include('reference.urls', namespace="reference")),
    path('admin/prod/', include('products.urls')),
    path('admin/', StaffHomeTemplateView.as_view()),
    
    path('user/', UserHomeTemplateView.as_view()),
    path('user/cart/', include('cart.urls')),
    path('user/order/', include('order.urls')),
    path('user/comments/', include('comments.urls')),
    path('user/search/', include('search.urls', namespace="search")),

    path('user/core/', include('core.urls', namespace="core")),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # redirect_url
# get_success_url(self):
# return  reverse_lazy(...., kwargs={pk = self.obj.id})
# get_request

# google material design


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),

#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),

#     ] + urlpatterns

cart/urls.py
from django.urls import path
from . import views
from .views import (AddProductToCartView, CartView, DelOrderView )


app_name = "cart"

urlpatterns = [
    path('add/<int:book>/', AddProductToCartView.as_view(), name="add"),
    path('bookcart/', CartView.as_view(), name="bookcart"),
    path('del/<int:pk>/', DelOrderView.as_view(), name="delete"),
]





    

order/urls.py
from django.urls import path
from . import views
from .views import (OrderCheckoutView, OrderCheckoutSuccess, OrdersListAdmin)


app_name = "order"

urlpatterns = [
    
    #path('incart/', OrderView.as_view(), name='order-in-cart'),
    path(
        'check-out/',
        views.OrderCheckoutView.as_view(),
        name="check-out"),
    path(
        'success/<int:pk>/',
        views.OrderCheckoutSuccess.as_view(),
        name="success"),

    path(
        'list-admin/',
        OrdersListAdmin.as_view(),
        name="list-admin"),

        ]
        # сделать ссылку на главной c object.pk/ статус в хтмл {{ object.status.name }}
#        1. гет контекст из детаил вью: выдергивает объект (order)
#        гет контекст выдает словарь (значения объекта)
#        гет контекст дата - влази в конец, перед отрисовкой страницы (лучше для меню и прочего)
#        2. второй вариант через гет_обджект (получает объект из модели, предпочтительнее для работы с объектами! )
#
# новая тема
#пагинация - постранично (для больших объемов!)
# paginate_by = 2 (по 2 объекта на странице)
# миксин занимается обработкой данных
# например миксин для отображения списка объектов (постранично)
# в урлах номер страницы
# специальное слово last (т.к. не изместно количество страниц)
# orphans - допис последнюю страницу (новая или предпоследн большая)
# в контекст - обджект-лист, ин-паджинэитыд, пагинатор
# {{ is.paginated }} boolean (сейчас работает ли пагинация - тру/да) для отображения кнопок важно 
# {{ paginator }}    
# можно добавить шаблон и инклудить его на все страницы, где будет пагинация
#
# новая тема
# аутентификация (кто ты? логин/пароль)   
# аутеризация (процесс узнавания того, что мне разрешено)
# админ, персонал, покупатель2
# next - возврат после логина на страницу, с которой перебросило на логин 


    
    

products/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import (CreateBook, UpdateBook, DetailBook, ListBook, 
DeleteBook, )
# from .apptoview import ListBooks

app_name = "products"

urlpatterns = [
    path('book/create/', CreateBook.as_view(), name = "book-create"),
    path('book/detail/<int:pk>/', DetailBook.as_view(), name = "book-detail"),
    path('book/list/', ListBook.as_view(), name = "book-list"),
    path('book/update/<int:pk>/', UpdateBook.as_view(), name = "book-update"),
    path('book/delete/<int:pk>/', DeleteBook.as_view(), name = "book-delete"),

#    path('book/listbooks/<int:pk>/', ListBooks.as_view(), name = "listbooks"),
] 

#if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Book

User = get_user_model()

class Cart(models.Model):
    user = models.ForeignKey(
        User,
        related_name='cart',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    created_date=models.DateTimeField(
        verbose_name='Создано',
        auto_now=False,
        auto_now_add=True,
    )
    update_date=models.DateTimeField(
        verbose_name='Изменено',
        auto_now=True,
        auto_now_add=False,
    )
    def __str__(self):
        return "Корзина №{} для пользователя {}".format(
            self.pk,
            self.user
        )
    @property
    def products_in_cart_count(self):
        total = 0
        for product in self.products_in_cart.all():
            total += product.quantity
        return total
    class Meta:
        verbose_name='Корзина',
        verbose_name_plural="Корзина"
        
class ProductsInCart(models.Model):
    cart = models.ForeignKey(
        Cart,
        verbose_name="Корзина",
        #для ссылки!(взять все дочерние сущности!)
        related_name='products_in_cart',
        on_delete=models.CASCADE
    )
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE
    )
    quantity = models.IntegerField(
        "Количество",
        default=1,
    )
    # returns the string representation of an object 
    def __str__(self):
        return "Книга {name} в корзине {cart_id}".format(
            name=self.book.name,
            cart_id=self.cart.pk,
        )



# Cart, Product - Uniquetogether нельзя одинаковые 

cart/forms.py
from django import forms
from django.forms import ModelForm
from .models import ProductsInCart


class AddToCartForm(ModelForm):
    class Meta:
        model = ProductsInCart
        fields = [
            'book', 
            'quantity'
        ]
        widgets = {
            'book': forms.HiddenInput()
        }



class CartForm(ModelForm):
    class Meta:
        model = ProductsInCart
        fields = [
            'book', 
            'quantity'
        ]
        widgets = {
            'book': forms.HiddenInput()
        }

cart/views.py
from django.shortcuts import render
from django.views.generic import (UpdateView, DetailView, DeleteView)

from .forms import (AddToCartForm, CartForm)
from order.forms import CheckCartForm
from .models import (Cart, ProductsInCart)
from products.models import Book
from reference.models import Status

class AddProductToCartView(UpdateView):
    # access to self.object, which is the object being updated    
    template_name = "add-to-cart.html"
    form_class = AddToCartForm
    model = ProductsInCart
    success_url = '/user/cart/bookcart/'
    # it fetchs the object 
    def get_object(self):
        # session dictionary keys
        cart_id = self.request.session.get('cart_id')
        # get parameters of defined object/book (from request!)
        book_id = self.kwargs.get('book')
        # created - boolean! Check: if cart with the given parameters exists - continue/update; else - create a new cart (using defaults).
        print(book_id)
        cart, cart_created = Cart.objects.get_or_create(
            pk = cart_id,
            defaults = {'user':self.request.user,}
        )
        # get book in cart with personal key = book_id
        book = Book.objects.get(pk=book_id)
        # check: looking up an obj with the given kwargs or creating a new obj
        book_in_cart, created = ProductsInCart.objects.get_or_create(
            cart = cart,
            book = book,
            defaults = {
            'cart':cart,
            'book':book,    
            'quantity':1
            },
        ) 
        if cart_created: 
            self.request.session['cart_id'] = cart.pk
        # add 1 in field quantity instead of doubling books 
        elif not created:
            book_in_cart.quantity += 1
        return book_in_cart
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['logo'] = "BOOKshop"
        return context

new_order_status = Status.objects.get(pk=1)

class CartView(DetailView):
    model = Cart
    template_name = 'cart.html'
    def get_object(self):
        cart_id = self.request.session.get('cart_id')
        cart, cart_created = Cart.objects.get_or_create(
            pk=cart_id,
            defaults={'user': self.request.user}
            )
        return cart
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        checkout_form = CheckCartForm()
        checkout_form.fields['cart'].initial = self.object
        checkout_form.fields['status'].initial = new_order_status
        context["form"] = checkout_form
        return context


class DelOrderView(DeleteView):
    model = ProductsInCart
    template_name = 'delete-in-cart.html'
    success_url = '/user/cart/bookcart/'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['delete'] = 'Удалить'
        return context    

cart/templates/add-to-cart.html
{% extends "base-core.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block title %}
Добавить в корзину
{% endblock title %}
    
{% block content %}


<div class="container">
    <br>
    <h4 class="alert alert-info" role="alert">Товар в корзине:</h4>

    <h1>"{{ object.book.name }}" {{ object.book.author.all|join:", "}}</h1> 
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-info">Отправить</button> 
        <a href="/user/"><button type="button" class="btn btn-outline-info">Отмена</button></a>
    </form>
</div>

{% endblock content %}

cart/templates/cart.html
{% extends "base-core.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block title %}
Корзина 
{% endblock title %}
    
{% block content %}

<div class="container">
    <br>
        <h4 class="alert alert-info" role="alert">Корзина № {{ cart.pk }} </h4>
            <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Книга</th>
                <th scope="col">Кол-во</th>
                <th scope="col">Цена</th>
                <th scope="col">..</th>
                </tr>
            </thead>
            <tbody>
        {% for object in object.products_in_cart.all %}
                <tr>
                <th scope="row">{{ object.book.pk }}</th>
                <td>{{ object.book.name }} </td>
                <td>{{ object.quantity }}</td>
                <td>{{ object.book.cost }}</td>
                <td>
                    <a href="{% url 'products:book-detail' object.book.pk %}"><button type="button" class="btn btn-info btn-sm">Просмотр</button></a>
                    <a href="{% url 'cart:add' object.book.pk %}"><button type="button" class="btn btn-info btn-sm">Ред-ть</button></a>
                    <a href="{% url 'cart:delete' object.pk %}"><button type="button" class="btn btn-info btn-sm">Удалить</button></a>
                </td>
                </tr>
        {% endfor %}

            </tbody>
            </table>
            {% if object.products_in_cart_count > 0 %}
            <div class="card bg-light border-primary mb-3">
                <h5 class="card-header border-primary">Оформить заказ</h5>
                    <form action="{% url 'order:check-out' %}" method="POST" class="card-body">
                        {% csrf_token %}
                        <h5 class="card-title">* - обязательны для заполнения</h5>
                        <p class="card-text">{{ form|crispy }}</p>
                        <button class="btn btn-danger btn-block" type="submit">Оформить заказ</button>
                    </form>
            </div>
            {% endif %}
</div>

{% endblock content %}

cart/templates/delete-in-cart.html
{% extends "base-core.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block title %}
BookShop доставка 
{% endblock title %}
    
{% block content %}

<div class="container">

{{ object.book.name }}
{{ object.quantity }}

<form action="" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-block">Удалить?</button>
</form>
</div>
{% endblock content %}